version: '3.0'

expectations:
  population_size: 1000

actions:
  vax_eligibility_inputs:
    run: r:latest analysis/vax_eligibility_inputs.R
    outputs:
      highly_sensitive:
        vax_study_dates_json: output/vax_study_dates.json
        vax_jcvi_groups: output/vax_jcvi_groups.csv
        vax_eligible_dates: output/vax_eligible_dates.csv

  # generate_study_population_vaccinated:
  #   run: cohortextractor:latest generate_cohort --study-definition study_definition_vaccinated
  #     --output-format feather
  #   outputs:
  #     highly_sensitive:
  #       cohort: output/input_vaccinated.feather