version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population_vaccinated:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_vaccinated
      --output-format feather
    outputs:
      highly_sensitive:
        cohort: output/input_vaccinated.feather