version: '3.0'

expectations:
  population_size: 1000

actions:
  vax_eligibility_inputs:
    run: r:latest analysis/vax_eligibility_inputs.R
    outputs:
      highly_sensitive:
        vax_study_dates_json: analysis/vax_study_dates.json
        vax_jcvi_groups: analysis/vax_jcvi_groups.csv
        vax_eligible_dates: analysis/vax_eligible_dates.csv

  # generate_study_population_vaccinated:
  #   run: cohortextractor:latest generate_cohort --study-definition study_definition_vaccinated
  #     --output-format feather
  #   outputs:
  #     highly_sensitive:
  #       cohort: analysis/input_vaccinated.feather

  generate_study_population_prelim:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_prelim
      --output-format feather
    outputs:
      highly_sensitive:
        cohort: output/input_prelim.feather

  generate_index_dates:
      run: r:latest analysis/prelim.R
      needs: 
      - generate_study_population_prelim
      outputs:
        highly_sensitive:
          index_dates: output/index_dates.feather
